### ISSUE TITLE
QA Checklist - Beta 1

### ISSUE THREAD

**Issue by defensivedepth** [defensivedepth/WinTAP#1]
- [x] Finish my changes @defensivedepth 
- [x] Push my commits to GitHub @defensivedepth 
- [ ] Open a pull request
